// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Header");

function make(message, size, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              switch (size) {
                case "h1" : 
                    return React.createElement("h1", undefined, message);
                case "h2" : 
                    return React.createElement("h2", undefined, message);
                case "h3" : 
                    return React.createElement("h3", undefined, message);
                case "h4" : 
                    return React.createElement("h4", undefined, message);
                case "h5" : 
                    return React.createElement("h5", undefined, message);
                case "h6" : 
                    return React.createElement("h6", undefined, message);
                case "h7" : 
                    return React.createElement("h7", undefined, message);
                default:
                  return React.createElement("h1", undefined, message);
              }
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
