// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as PlayerList$Nfldraftreason from "./PlayerList.bs.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, PlayerList$Nfldraftreason.make(/* array */[])), "root");

export {
  
}
/*  Not a pure module */
