// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Component1$Nfldraftreason from "./Component1.bs.js";
import * as Component2$Nfldraftreason from "./Component2.bs.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Component1$Nfldraftreason.make("Hello!", /* array */[])), "index1");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Component2$Nfldraftreason.make("nick!", /* array */[])), "index2");

export {
  
}
/*  Not a pure module */
