// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Button$Nfldraftreason from "./Button.bs.js";
import * as Player$Nfldraftreason from "./Player.bs.js";

var rootUrl = "http://localhost:8080/";

function p(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.$$int, json),
          /* name */Json_decode.field("name", Json_decode.string, json),
          /* school */Json_decode.field("school", Json_decode.string, json),
          /* position */Json_decode.field("position", Json_decode.string, json),
          /* drafted */Json_decode.field("drafted", Json_decode.bool, json)
        ];
}

function players(json) {
  return Json_decode.array(p, json);
}

var Decode = /* module */[
  /* p */p,
  /* players */players
];

function sendQuery(evt) {
  console.log(evt);
  return /* () */0;
}

var component = ReasonReact.reducerComponent("PlayerList");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              return Curry._1(self[/* send */3], /* PlayersFetch */0);
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1];
              if (typeof match === "number") {
                if (match !== 0) {
                  return React.createElement("div", undefined, "Loading...");
                } else {
                  return React.createElement("div", undefined, "An error occurred!");
                }
              } else {
                return React.createElement("div", undefined, React.createElement("h3", undefined, "Players"), React.createElement("ul", undefined, $$Array.map((function (player) {
                                      return React.createElement("li", {
                                                  key: String(player[/* id */0])
                                                }, ReasonReact.element(undefined, undefined, Player$Nfldraftreason.make(player, /* array */[])));
                                    }), match[0])), ReasonReact.element(undefined, undefined, Button$Nfldraftreason.make((function () {
                                      return Curry._1(self[/* send */3], /* PlayersFetch */0);
                                    }), "Submit", /* array */[])));
              }
            }),
          /* initialState */(function () {
              return /* Loading */1;
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              if (typeof action === "number") {
                return /* UpdateWithSideEffects */Block.__(2, [
                          /* Loading */1,
                          (function (self) {
                              fetch("http://localhost:8080/players/").then((function (prim) {
                                          return prim.json();
                                        })).then((function (json) {
                                        var players = Json_decode.array(p, json);
                                        return Promise.resolve(Curry._1(self[/* send */3], /* PlayersFetched */Block.__(0, [players])));
                                      })).catch((function (err) {
                                      return Promise.resolve(Curry._1(self[/* send */3], /* PlayersFailedToFetch */Block.__(1, [err])));
                                    }));
                              return /* () */0;
                            })
                        ]);
              } else if (action.tag) {
                return /* Update */Block.__(0, [/* Error */0]);
              } else {
                return /* Update */Block.__(0, [/* Loaded */[action[0]]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  rootUrl ,
  Decode ,
  sendQuery ,
  component ,
  make ,
  
}
/* component Not a pure module */
