// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Curry = require("bs-platform/lib/js/curry.js");

describe("Sanity check", (function () {
        return Jest.test("toBe", (function () {
                      return Jest.Expect[/* toBe */2](3, Jest.Expect[/* expect */0](3));
                    }));
      }));

describe("Expect.Operators", (function () {
        return Jest.test("==", (function () {
                      return Curry._2(Jest.Expect[/* Operators */25][/* == */0], Jest.Expect[/* expect */0](3), 3);
                    }));
      }));

describe("Button should render the text (message) passed to it", (function () {
        return Jest.test("==", (function () {
                      return Curry._2(Jest.Expect[/* Operators */25][/* == */0], Jest.Expect[/* expect */0](3), 3);
                    }));
      }));

/*  Not a pure module */
